-
  name: Deploy a web application
  hosts: db_and_web_servers
  tasks:
    - name: Install all required dependencies
      yum:
        name: '{{ item }}'
        state: installed
      with_items:
        - python
        - python-setuptools
        - python-devel
        - epel-release

    - name: Install MySQL Community Repository
      yum:
        name: "http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm"
        state: present

    - name: Install MySQL Database
      yum:
        name: '{{ item }}'
        state: installed
      with_items:
        - mysql-server
        - mysql-devel

    - name: Start Database Service
      service:
        name: mysql
        state: started
        enabled: yes
